# -*- mode: ruby -*-
# vi: set ft=ruby :

if (ARGV & %w(up provision)).any?
  exit 1 unless system('ansible-galaxy install -f -r requirements.yml -p ./roles')
end

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "phusion/ubuntu-14.04-amd64"

  # Forward the registry port
  config.vm.network "forwarded_port", guest:443, host:4443
  config.vm.network "forwarded_port", guest:80, host:8080
  config.vm.network "forwarded_port", guest:8080, host:8888

  config.vm.define 'machine1' do |machine|
    machine.vm.hostname = 'machine1'
    machine.vm.provision "ansible" do |ansible|
      ansible.verbose = true
      ansible.playbook = "test.yml"
      ansible.extra_vars = {
          role_name: Dir.pwd.split('/')[-2]
        }
    end
  end
end
